export const projectDescriptions: Record<string, string[]> = {
  sencelles: [
    "En Dosmas Grup entendemos la construcción de una vivienda como un proceso complejo que exige experiencia, visión global, coordinación constante y un compromiso absoluto con la calidad en cada fase de la obra. Actualmente, nuestra empresa está llevando a cabo la construcción de dos chalets de 500 metros cuadrados en el municipio de Sencelles, un proyecto que refleja a la perfección nuestra capacidad para asumir obras de gran envergadura con solvencia, seriedad y máxima implicación.",
    "Se trata de dos viviendas concebidas para ofrecer amplitud, confort, funcionalidad y una integración armónica con el entorno. En ambos casos, en Dosmas Grup estamos desarrollando todo el proceso constructivo, desde los primeros trabajos de excavación y cimentación, hasta la estructura, la evolución completa de la obra y sus acabados finales. Esta capacidad de abordar un proyecto de principio a fin es uno de los grandes valores diferenciales de nuestra empresa, ya que nos permite garantizar un control riguroso sobre cada detalle, una ejecución bien planificada y una coordinación eficaz entre todas las fases del trabajo.",
    "Además de la propia edificación, estas dos viviendas contarán con piscina y jardín, elementos que completan el conjunto y que exigen el mismo nivel de precisión, planificación y conocimiento técnico que el resto de la obra. En este sentido, Dosmas Grup también asume la ejecución de la piscina y todo el proyecto de ajardinamiento, reafirmando así nuestra capacidad para ofrecer soluciones integrales y responder con garantías a proyectos residenciales de gran dimensión.",
    "Uno de los aspectos más destacados de esta actuación es, sin duda, el respeto por la esencia del paisaje y de la construcción tradicional mallorquina. En ambas casas hemos ejecutado los trabajos de pared seca, una técnica profundamente arraigada en la identidad constructiva de nuestra tierra. En total, se han realizado más de 1.000 metros lineales de pared de piedra seca, un trabajo que no solo aporta carácter, autenticidad y valor estético al conjunto, sino que también pone de manifiesto nuestra sensibilidad hacia el entorno y hacia las formas tradicionales de construir en Mallorca.",
    "La pared seca forma parte del patrimonio visual y cultural de la isla. Integrarla en un proyecto actual significa mantener viva una manera de hacer que habla de territorio, oficio y respeto por lo que nos identifica. En Dosmas Grup creemos firmemente que avanzar no significa renunciar a la tradición, sino saber incorporarla con inteligencia, equilibrio y coherencia dentro de proyectos contemporáneos.",
    "Afrontar una obra de estas características requiere mucho más que maquinaria y medios técnicos. Requiere un equipo humano altamente preparado, una estructura de trabajo bien organizada y una capacidad real para mantener el ritmo, la precisión y la coordinación durante todo el proceso. En Dosmas Grup contamos con esa capacidad de trabajo constante y bien sincronizado que resulta imprescindible para ejecutar obras exigentes con seguridad, eficacia y garantía de resultado.",
    "La seguridad en obra es, además, una prioridad irrenunciable en cada proyecto que asumimos. Cada intervención, cada fase y cada decisión se lleva a cabo bajo criterios de responsabilidad y control, porque entendemos que construir bien también significa construir con orden, con previsión y con el máximo respeto por las personas que hacen posible cada avance.",
    "Estos dos proyectos en Sencelles son un ejemplo claro de la forma en que trabajamos en Dosmas Grup: abordando cada obra con una visión integral, cuidando desde la base estructural hasta el último acabado, ejecutando espacios exteriores con la misma exigencia que el interior, y respetando siempre el carácter del entorno en el que intervenimos.",
    "Porque cuando una vivienda se construye con planificación, experiencia, coordinación y compromiso, el resultado va mucho más allá de los metros cuadrados. Se convierte en un espacio pensado para perdurar, para convivir con el paisaje y para ofrecer bienestar, solidez y valor con el paso del tiempo.",
    "En Dosmas Grup construimos viviendas de gran dimensión con la seriedad, la capacidad y la dedicación que exige cada gran proyecto."
  ],
  valldemossa: [
    "En DOSMAS GRUP entendemos la construcción como algo más que levantar estructuras. Cada proyecto es un proceso vivo, una suma de decisiones, conocimiento y compromiso que empieza mucho antes del primer movimiento de tierra y se prolonga hasta el último detalle. Así lo demuestra la vivienda que actualmente estamos construyendo en Valldemossa, en pleno corazón de la Serra de Tramuntana.",
    "Ubicada en uno de los entornos naturales más emblemáticos de Mallorca, esta casa nace con la voluntad de integrarse en el paisaje, respetando su esencia y dialogando con la arquitectura tradicional de la zona desde una mirada contemporánea.",
    "Mucho más que construir una casa",
    "En DOSMAS GRUP no solo construimos viviendas: las cuidamos, las pensamos y las acompañamos en cada fase de su desarrollo. Desde los cimientos hasta los acabados finales, cada decisión responde a un objetivo claro: crear espacios duraderos, funcionales y capaces de transmitir bienestar.",
    "Detrás de cada obra existe una promesa silenciosa, pero firme: seleccionar materiales que perduren en el tiempo, aplicar procesos constructivos rigurosos y trabajar con un equipo humano que afronta cada proyecto como si fuera propio. Esta manera de entender la construcción es la que permite alcanzar resultados donde la calidad no solo se aprecia a simple vista, sino que también se siente en el uso diario.",
    "Calidad que perdura",
    "La vivienda, actualmente en proceso de construcción, refleja la filosofía que ha definido a DOSMAS GRUP durante décadas: apostar por soluciones sólidas, eficientes y pensadas para acompañar toda una vida. Cada elemento se ejecuta con precisión técnica y sensibilidad estética, buscando el equilibrio entre tradición, innovación y respeto por el entorno natural.",
    "Porque cuando construimos, no solo levantamos espacios habitables; construimos confianza. Y esa confianza se percibe en cada detalle, en cada acabado y en cada proyecto entregado."
  ],
  portocolom: [
    "En Dosmas Grup continuamos desarrollando proyectos que contribuyen de forma directa a mejorar el entorno, optimizar los espacios públicos y avanzar hacia un modelo de desarrollo más sostenible. Dentro de esta línea de trabajo, recientemente hemos finalizado una importante actuación en s’Arenal de Portocolom, una obra que ha permitido recuperar un espacio clave del litoral y transformarlo en una zona más accesible, ordenada y respetuosa con su entorno.",
    "La intervención ha supuesto una mejora significativa tanto desde el punto de vista urbanístico como ambiental. Uno de los aspectos más destacados del proyecto ha sido la eliminación del antiguo vial junto a la playa, una actuación que ha permitido replantear por completo la relación de este espacio con su entorno natural y con las personas que lo disfrutan a diario.",
    "A partir de esta transformación, se ha creado una gran zona verde y peatonal, concebida para favorecer un uso más amable del espacio público, potenciar la integración paisajística y ofrecer un entorno más cómodo y seguro para peatones y visitantes. Esta nueva configuración contribuye a recuperar el valor del litoral como lugar de encuentro, paseo y disfrute, priorizando la calidad urbana y el respeto medioambiental.",
    "El proyecto también ha incluido la instalación de una pasarela de madera y de pavimentos ecológicos, elementos que refuerzan el carácter sostenible de la actuación y que permiten una mejor integración de la obra en un entorno especialmente sensible. La elección de soluciones constructivas adaptadas al lugar ha sido clave para alcanzar un resultado equilibrado, funcional y en armonía con el paisaje.",
    "Asimismo, la obra ha contemplado la creación de un nuevo aparcamiento de 28 plazas en es Tancat de sa Torre, dando respuesta a las necesidades de estacionamiento de la zona desde una planificación más ordenada y eficiente. Esta nueva dotación contribuye a reorganizar la movilidad del entorno y a reducir la presión del tráfico rodado en el frente litoral.",
    "Precisamente, otro de los grandes objetivos de la actuación ha sido la mejora de la movilidad y la reducción del tráfico rodado, favoreciendo una convivencia más equilibrada entre vehículos, peatones y entorno urbano. Se trata de una intervención que no solo transforma físicamente un espacio, sino que también mejora su funcionalidad, su accesibilidad y su calidad ambiental.",
    "En Dosmas Grup entendemos la obra pública como una herramienta de transformación real del territorio. Por ello, ejecutamos cada proyecto con criterios técnicos exigentes, con responsabilidad ambiental y con una clara voluntad de integración urbana. La actuación realizada en s’Arenal de Portocolom es un buen ejemplo de esta manera de trabajar: una obra pensada para mejorar el presente, pero también para aportar valor duradero al entorno.",
    "Este proyecto refleja nuestro compromiso con una obra pública de calidad, capaz de responder a las necesidades actuales sin renunciar al respeto por el paisaje, la funcionalidad de los espacios y el bienestar de las personas.",
    "En Dosmas Grup seguimos construyendo infraestructuras y espacios que mejoran Mallorca desde la seriedad, la experiencia y una visión responsable del desarrollo."
  ],
  aeropuertoDePalmaReciclaje: [
    "En Dosmas Grup creemos firmemente que cada obra es mucho más que un trabajo ejecutado con maquinaria y experiencia. Cada proyecto representa una oportunidad para demostrar quiénes somos, cómo trabajamos y cuáles son los valores que nos mueven. Por eso, participar en los importantes trabajos de reciclaje de material de derribo en el aeropuerto de Palma supone para nuestra empresa un motivo de auténtico orgullo.",
    "Nos encontramos inmersos en una actuación de gran relevancia, tanto por su envergadura como por su significado. Hasta el momento, hemos reciclado en esta obra alrededor de 25.000 metros cúbicos de material, una cifra que da muestra de la magnitud de los trabajos y de la capacidad técnica y humana necesaria para llevarlos a cabo con eficacia, rigor y responsabilidad.",
    "Este proyecto cuenta con un importante despliegue de medios, entre los que destacan dos giratorias JCB de 22 toneladas, una pala Caterpillar 996, una pala Caterpillar 962, una machacadora Kleemann, una cribadora vibradora Frontier Keestrack y diez camiones, además de la implicación constante de un equipo humano altamente cualificado. Porque si hay algo que define a Dosmas Grup no es únicamente su maquinaria o su experiencia acumulada durante décadas, sino el compromiso y la profesionalidad de las personas que hacen posible cada avance sobre el terreno.",
    "Más allá del reto técnico, esta obra tiene un valor especialmente significativo por su componente ambiental. Todo el material reciclado se reutiliza en las propias instalaciones del aeropuerto de Palma, lo que convierte esta actuación en un magnífico ejemplo de aprovechamiento de recursos y de gestión responsable dentro del propio entorno de obra. Allí donde antes hubo derribo, ahora hay una nueva oportunidad de uso. Allí donde otros verían un residuo, nosotros vemos una materia valiosa que, tratada correctamente, puede seguir formando parte del progreso.",
    "El reciclaje en el ámbito de la construcción es hoy una necesidad incuestionable. No solo contribuye a reducir el impacto ambiental de las obras, sino que también fomenta una manera de trabajar más eficiente, más consciente y más alineada con las exigencias del presente y del futuro. Apostar por reutilizar materiales es apostar por una construcción más inteligente, por una optimización real de los recursos y por una visión de largo recorrido en la que sostenibilidad y desarrollo deben avanzar de la mano.",
    "En Dosmas Grup asumimos esta responsabilidad con la seriedad que merece. Sabemos que trabajar en un enclave tan relevante como el aeropuerto de Palma exige el máximo nivel de exigencia, planificación y solvencia. Y precisamente por eso, formar parte de este proyecto nos llena de satisfacción. Es un orgullo poder aportar nuestra experiencia, nuestra capacidad operativa y nuestro modo de entender el trabajo bien hecho a una actuación que combina rendimiento, sostenibilidad y utilidad real.",
    "Seguimos avanzando con la misma convicción de siempre: la de ofrecer soluciones eficaces, afrontar grandes retos con garantías y demostrar, una vez más, que detrás de cada proyecto importante hay un equipo preparado para dar lo mejor de sí mismo.",
    "Porque en Dosmas Grup no solo movemos materiales.",
    "Transformamos espacios, optimizamos recursos y ayudamos a construir un futuro más responsable."
  ],
  construccionCasaEnSonVida: [
    "En DOSMAS GRUP entendemos cada proyecto como una oportunidad para materializar espacios únicos, pensados para perdurar en el tiempo y adaptarse plenamente al estilo de vida de quienes los habitan. Un claro ejemplo de ello es la reciente construcción de una vivienda unifamiliar en Son Vida, una de las urbanizaciones residenciales más exclusivas y reconocidas de Mallorca.",
    "La actuación consistió en la edificación de una residencia de aproximadamente 1.000 m2, concebida bajo criterios de arquitectura contemporánea y diseñada para integrarse con armonía en su entorno natural. El proyecto incorpora una amplia piscina y cuidadas zonas ajardinadas que dialogan con la vivienda, generando un conjunto equilibrado donde interior y exterior se conectan de forma fluida.",
    "Diseño, calidad y precisión técnica",
    "Desde el inicio de la obra, el objetivo fue claro: alcanzar los más altos estándares constructivos. Para ello, se apostó por materiales de primer nivel, seleccionados tanto por su valor estético como por su durabilidad y eficiencia. La ejecución combinó soluciones técnicas avanzadas con una cuidada atención al detalle, logrando acabados que reflejan elegancia, sobriedad y calidad.",
    "Cada fase del proceso constructivo se desarrolló bajo un exhaustivo control técnico, garantizando la correcta planificación de los trabajos, la optimización de recursos y el cumplimiento de los plazos establecidos. Este enfoque permitió asegurar no solo la solidez estructural del proyecto, sino también una ejecución eficiente y respetuosa con el entorno.",
    "Construcción de lujo con garantía de experiencia",
    "La realización de esta vivienda en Son Vida reafirma la trayectoria de DOSMAS GRUP en el ámbito de la construcción residencial de alto nivel. Con más de 70 años de experiencia, la empresa continúa consolidándose como un referente capaz de afrontar proyectos complejos, donde la precisión técnica, la calidad constructiva y la confianza del cliente son elementos esenciales.",
    "El resultado es un espacio que une confort, estética y durabilidad, pensado para ofrecer bienestar a largo plazo y responder a las exigencias de uno de los enclaves residenciales más prestigiosos de la isla.",
    "En Dosmas Grup seguimos construyendo futuro, transformando ideas en realidades sólidas y espacios diseñados para ser vividos."
  ],
  costaDeLosPinos: [
    "En DOSMAS GRUP entendemos que cada vivienda es mucho más que una obra: es un proyecto de vida. Actualmente trabajamos en la construcción de una casa de grandes dimensiones en Costa de los Pinos (Son Servera), un enclave privilegiado del litoral mallorquín donde la arquitectura y el entorno natural conviven en equilibrio.",
    "Este proyecto destaca por la aplicación de primeras calidades constructivas, tanto en los sistemas estructurales como en los materiales seleccionados, respondiendo a las exigencias propias de una vivienda de alto nivel. Sin embargo, más allá de sus dimensiones o de su ubicación, lo que realmente define esta obra es la filosofía con la que ha sido concebida y ejecutada.",
    "Pensar cada casa como única",
    "En DOSMAS GRUP no solo construimos viviendas: las cuidamos, las pensamos y las desarrollamos desde el primer cimiento hasta el último detalle. Cada fase del proceso se aborda con planificación, rigor técnico y una visión global que permite anticipar necesidades y garantizar resultados duraderos.",
    "En proyectos como el de Costa de los Pinos existe una promesa silenciosa que guía nuestro trabajo: elegir materiales que resistan el paso del tiempo, aplicar procesos impecables y contar con un equipo humano que trabaja con la misma dedicación que si cada casa fuera propia.",
    "Calidad que trasciende el tiempo",
    "La calidad se percibe en los acabados, en la solidez de la construcción y en la armonía del conjunto. Es una calidad que se ve, pero también se siente en la experiencia diaria de quienes habitarán el espacio. Una calidad pensada para acompañar toda una vida, aportando confort, seguridad y tranquilidad.",
    "Porque cuando Dosmas Grup construye, no solo levanta edificaciones: construye confianza. Y esa confianza, fruto de la experiencia y del compromiso constante con la excelencia, es lo que convierte cada proyecto en algo verdaderamente especial."
  ],
  excavacionEnSonVida: [
    "En DOSMAS GRUP, cada proyecto representa un nuevo reto técnico y una oportunidad para demostrar la capacidad y experiencia acumuladas a lo largo de más de 70 años de trayectoria. Hace poco, la empresa ha llevado a cabo una excavación de gran envergadura en la exclusiva urbanización de Son Vida, uno de los enclaves residenciales más prestigiosos de España y referente del lujo residencial en Mallorca.",
    "Un proyecto que exige máxima precisión",
    "Trabajar en un entorno como Son Vida implica afrontar condiciones técnicas exigentes, donde la planificación, la seguridad y la precisión son factores determinantes. La actuación tiene como objetivo preparar el terreno para futuras construcciones de alto nivel, garantizando una base sólida y perfectamente adaptada a las necesidades del proyecto arquitectónico.",
    "Para alcanzar estos estándares, DOSMAS GRUP ha desplegado maquinaria de última generación, entre la que destacan las potentes excavadoras Caterpillar 352 y Liebherr 944, equipos diseñados para ejecutar movimientos de tierra complejos con la máxima eficiencia y control. A ello se suma una flota de camiones Renault, Volvo y Scania, que permite optimizar la logística de transporte y asegurar un ritmo de trabajo constante y preciso.",
    "Innovación y experiencia al servicio del terreno",
    "La combinación de tecnología avanzada y un equipo humano altamente cualificado permite desarrollar los trabajos con rapidez, seguridad y rigor técnico. Cada fase de la excavación se ejecuta siguiendo estrictos protocolos de control, minimizando el impacto en el entorno y garantizando resultados acordes con las exigencias de un proyecto ubicado en un entorno residencial de primer nivel.",
    "Esta intervención refleja el compromiso permanente de DOSMAS GRUP con la excelencia técnica y la innovación, valores que han acompañado a la empresa desde sus inicios y que continúan marcando su forma de trabajar.",
    "Liderazgo en excavaciones complejas",
    "Con una sólida trayectoria en obras civiles y movimientos de tierra, DOSMAS GRUP reafirma su posición como empresa referente en excavaciones complejas y proyectos de alta exigencia técnica. La experiencia acumulada, junto con la constante inversión en maquinaria y tecnología, permite afrontar actuaciones de gran escala con plena garantía.",
    "La excavación en Son Vida es un ejemplo más de cómo la combinación entre conocimiento, medios técnicos y profesionalidad convierte cada proyecto en una base firme sobre la que construir el futuro."
  ],
  remodelacionPlacaDesMercat: [
    "Los espacios públicos son mucho más que lugares de paso. Son escenarios de convivencia, puntos de encuentro y enclaves que forman parte de la identidad de un pueblo. Con esta visión, Dosmas Grup ha llevado a cabo la remodelación integral de la Plaça des Mercat, en Maria de la Salut, una actuación destinada a renovar este espacio emblemático y convertirlo en un entorno más amable, funcional y acogedor para vecinos y visitantes.",
    "La intervención ha sido concebida para transformar la plaza en un verdadero centro de vida social, respetando su esencia y reforzando su papel como lugar de encuentro para la comunidad. El proyecto ha permitido dar una nueva dimensión a este enclave urbano, dotándolo de una imagen renovada y de mejores condiciones para el uso diario.",
    "Entre las principales actuaciones realizadas destaca el nuevo adoquinado, que aporta solidez, uniformidad y armonía al conjunto del espacio. Esta mejora no solo refuerza la calidad estética de la plaza, sino que también contribuye a su durabilidad y funcionalidad, adaptándola a las necesidades actuales del municipio.",
    "La remodelación también ha incorporado arbolado y zonas verdes, elementos fundamentales para humanizar el entorno, generar frescor y enriquecer la experiencia de quienes lo disfrutan cada día. La presencia de vegetación introduce una nueva relación entre el espacio urbano y el bienestar de las personas, creando una plaza más viva, más agradable y mejor integrada en el paisaje del municipio.",
    "Asimismo, el proyecto ha contemplado la creación de un espacio de juegos pensado para que los más pequeños puedan disfrutar con seguridad. Esta incorporación refuerza el carácter familiar de la Plaça des Mercat y amplía sus posibilidades de uso, favoreciendo la convivencia intergeneracional y el disfrute compartido del espacio público.",
    "El resultado es una plaza abierta, preparada para pasear, compartir y reencontrarse. Un lugar que no solo responde a criterios urbanísticos y funcionales, sino que también aspira a convertirse en parte activa de la vida cotidiana de Maria de la Salut. La nueva Plaça des Mercat es, en este sentido, mucho más que un espacio reformado: es un lugar donde generaciones enteras podrán seguir escribiendo historias de convivencia, tradición y futuro.",
    "Para Dosmas Grup, esta actuación representa una nueva muestra de su compromiso con la mejora de los espacios públicos de Mallorca. Con más de 70 años de trayectoria, la empresa continúa desarrollando proyectos que combinan experiencia, calidad constructiva y una clara vocación de servicio al territorio.",
    "La remodelación integral de la Plaça des Mercat refleja esa manera de entender la obra pública: construir con rigor, transformar con sensibilidad y crear espacios pensados para la vida."
  ],
  esFigueralMarratxi: [
    "En Dosmas Grup seguimos sumando proyectos que contribuyen de forma directa a mejorar los espacios públicos de Mallorca y la calidad de vida de sus ciudadanos. Actualmente, nuestra empresa está ejecutando una importante obra pública en Es Figueral, en Marratxí, concretamente en la zona cercana a la estación de tren, donde se está llevando a cabo una actuación de gran utilidad para vecinos y visitantes.",
    "Los trabajos consisten en el acondicionamiento del terreno que posteriormente será asfaltado para crear un total de 266 plazas de aparcamiento, una infraestructura pensada para dar respuesta a las necesidades de movilidad y estacionamiento de esta zona. Se trata de una actuación importante, práctica y necesaria, que contribuirá a ordenar mejor el entorno y a facilitar el día a día de quienes transitan y utilizan este espacio.",
    "Pero esta obra va más allá de la creación de nuevas plazas de parking. El proyecto también contempla la ejecución de un carril bici y de una amplia zona peatonal, apostando así por un modelo de urbanización más accesible, más cómodo y mejor adaptado a una convivencia equilibrada entre vehículos, peatones y formas de movilidad más sostenibles.",
    "Este tipo de actuaciones reflejan a la perfección la importancia de una obra pública bien planificada y bien ejecutada. No solo transforman físicamente un entorno, sino que generan mejoras reales en su funcionalidad, en su seguridad y en la experiencia diaria de las personas que lo utilizan. En Dosmas Grup entendemos cada intervención como una responsabilidad y, al mismo tiempo, como una oportunidad para aportar nuestra experiencia y capacidad de trabajo al servicio del interés general.",
    "Para afrontar proyectos de esta envergadura, en Dosmas Grup contamos con dos pilares fundamentales: una gran flota de maquinaria, preparada para responder con eficacia a las exigencias de cualquier actuación, y un excelente equipo humano, formado por profesionales comprometidos, cualificados y acostumbrados a trabajar con rigor en todo tipo de obras públicas en Mallorca. Esa combinación de medios técnicos y talento humano es la que nos permite asumir con garantías cada nuevo reto y ejecutarlo con la máxima solvencia.",
    "Queremos expresar además nuestro más sincero agradecimiento al Ayuntamiento de Marratxí por la confianza depositada en nuestra empresa para la ejecución de estos trabajos. Para Dosmas Grup es un orgullo poder participar en proyectos que tienen una repercusión directa sobre el territorio y sobre la vida de las personas, contribuyendo al desarrollo de infraestructuras útiles, modernas y duraderas.",
    "Seguimos trabajando con la misma filosofía que nos ha acompañado siempre: compromiso, capacidad, seriedad y voluntad de ofrecer el mejor resultado en cada obra.",
    "En Dosmas Grup, ponemos nuestra experiencia, nuestra maquinaria y nuestro equipo humano al servicio de Mallorca"
  ],
  casConcos: [
    "La transformación de los espacios públicos es, en muchas ocasiones, una forma de cuidar la memoria de un pueblo mientras se construye su futuro. En Cas Concos, esa idea ya es una realidad. La reforma de la Plaça de l’Església, uno de los enclaves más representativos del núcleo urbano, ha quedado terminada, culminando así una intervención largamente esperada por vecinos y visitantes.",
    "El pasado 10 de septiembre, coincidiendo con las festividades de Sant Nicolau de Tolentí, tuvo lugar la colocación de la primera piedra de este proyecto emblemático promovido por el Ajuntament de Felanitx. Aquel acto simbolizó el inicio de una obra llamada a renovar uno de los espacios con mayor valor social, histórico y simbólico de Cas Concos. Hoy, con los trabajos ya finalizados, la plaza presenta una nueva imagen, más funcional, más accesible y mejor preparada para responder a las necesidades de la ciudadanía.",
    "El proyecto, redactado por los arquitectos Jaume Alomar Sureda y Xavier Fontanet Adrover, de Misión 21 Arquitectos S.L.P., fue adjudicado a Dosmas Grup, que ha asumido la ejecución de unas obras de especial relevancia para el municipio. Con un presupuesto de 554.000 euros, financiado con fondos europeos, esta actuación ha permitido recuperar y dignificar un espacio esencial para la vida colectiva del pueblo.",
    "La intervención ha supuesto mucho más que una mejora estética. La nueva Plaça de l’Església ha sido concebida como un entorno pensado para el encuentro, la convivencia y el uso cotidiano, capaz de acoger actividades colectivas y de reforzar la centralidad social del lugar. Todo ello, desde una mirada respetuosa con la identidad del entorno y con la voluntad de preservar el carácter histórico que define este espacio tan querido por los vecinos.",
    "Para Dosmas Grup, haber llevado a cabo esta obra representa una nueva muestra de su compromiso con las infraestructuras públicas que contribuyen a mejorar la calidad de vida de los pueblos de Mallorca. La reforma de la plaza de Cas Concos responde a una forma de entender la construcción basada en la responsabilidad, el rigor técnico y el respeto por el territorio.",
    "Esta actuación une tradición y modernidad en un mismo proyecto. Por un lado, mantiene la esencia y el valor patrimonial del lugar; por otro, introduce una transformación urbana que mira al futuro desde criterios de funcionalidad, sostenibilidad e integración. El resultado es un espacio renovado que seguirá formando parte de la vida del municipio durante muchos años.",
    "Con la finalización de esta obra, Dosmas Grup consolida una vez más su posición como empresa de referencia en la ejecución de proyectos públicos de relevancia en Mallorca, aportando experiencia, solvencia y una clara vocación de servicio en cada intervención."
  ]
};
